name: Package

on:
  push:
    paths:
      - "src/**"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project
      - name: Build with Maven
        run: mvn clean package

      - name: Create artifacts directory
        run: mkdir -p artifacts

      # Move the JAR file to the specified path
      - name: Move JAR to artifacts directory
        run: mv target/prune-daemon*-jar-with-dependencies.jar artifacts/app.jar

      - uses: actions/upload-artifact@v4
        id: upload-jar-artifact
        with:
          name: jar
          path: artifacts/app.jar
          overwrite: 'true'

      - uses: actions/upload-artifact@v4
        id: upload-docker-artifact
        with:
          name: Dockerfile
          path: Dockerfile
          overwrite: 'true'