name: Build Docker Image

on:
  workflow_run:
    workflows: ["Package"]
    types: [completed]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.download.outputs.download-path }}
    steps:
      - name: Download JAR file
        id: download-jar
        uses: actions/download-artifact@v4
        with:
          name: jar
          github-token: ${{ github.token }}
          repository: '${{ github.repository }}'
          merge-multiple: 'true'
          run-id: TBD

      - name: Download Dockerfile
        id: download-docker
        uses: actions/download-artifact@v4
        with:
          name: Dockerfile
          github-token: ${{ github.token }}
          repository: '${{ github.repository }}'
          merge-multiple: 'true'
          run-id: TBD

      - name: Show files Downloaded
        run: ls -R

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: charity1475/prune-daemon:${{ github.sha }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}